spring.application.name=ecom

# Enable the H2 console
spring.h2.console.enabled=true

# Configure the H2 database connection
# Use a specific name for the in-memory database
spring.datasource.url=jdbc:h2:mem:test
spring.jpa.open-in-view=false

# Set custom username and password
spring.datasource.username=user
#spring.datasource.password=user

# This property enables the logging of all executed SQL statements to the standard output (the console).
spring.jpa.show-sql=true
# This property tells Hibernate to format the logged SQL queries, making them more readable.
spring.jpa.properties.hibernate.format_sql=true

# Hibernate to automatically create the database schema on application startup
# and then drop all tables when the application stops.
spring.jpa.hibernate.ddl-auto=create-drop
