spring.application.name=ecom

# Enable the H2 console
spring.h2.console.enabled=true

# Configure the H2 database connection
# Use a specific name for the in-memory database
spring.datasource.url=jdbc:h2:mem:test
spring.jpa.open-in-view=false

# Set custom username and password
spring.datasource.username=user
#spring.datasource.password=user
